### ISSUE TITLE
Add player behavior

### ISSUE THREAD

**Issue by NotBad4U** [agtors/agar.core#9]
A player should be able to:

- [x] Move toward a target (any point of the map)  #1
- [x] Pursuit another player #2 
- [x] Evade a pursuer #2 
- [x] Move toward a resource  #1
- [x] Consume a resource
- [x] Knowledge of entities in its area of interest.
- [x] Discover entities in a other system #7 
- [x] Wander when he has nothing to do 

The player will act only when it's his turn to play. That'll be orchestrate by the `Arbitrator`.
 The player (Cell) should only output one action (not sure to be clear here) when it's his turn e.g.: A player can Move or consume a resource but not do the both in the same turn.
I think that'll make the code more simple and limit the number of message emit.

## Explanations

> Discover entities close to his area of interest

![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAQQ7L3KarcW7zjvT5GobL1Ok3bQ3Gzfb4EFwKZbnnOaXyMhAqGg)
We can illustrate this with this picture where no entities or close to him so he don't need to know about them but if an entity come close to him he must be informed for that. That work for entities in a neighbor system see #7. Maybe the region actor #4 can do this work.

> Discover entities when he in another system

Moving Between Maps need to make a `discover` of close resources and inform other player that happend.

**Comment by NotBad4U** [comment]
With the merge of #31 #15 #26 #21 we can close this one
